from skimage import io
import numpy as np
import os
image = io.imread('textures/1.1.01.tiff')
print('Grass,'+str(np.mean(image)))
image = io.imread('textures/1.1.02.tiff')
print('Bark,'+str(np.mean(image)))
image = io.imread('textures/1.1.03.tiff')
print('Straw,'+str(np.mean(image)))
image = io.imread('textures/1.1.04.tiff')
print('Herringbone weave,'+str(np.mean(image)))
image = io.imread('textures/1.1.05.tiff')
print('Herringbone weave,'+str(np.mean(image)))
image = io.imread('textures/1.1.06.tiff')
print('Pressed calf leather,'+str(np.mean(image)))
image = io.imread('textures/1.1.07.tiff')
print('Beach sand,'+str(np.mean(image)))
image = io.imread('textures/1.1.08.tiff')
print('Water,'+str(np.mean(image)))
image = io.imread('textures/1.1.09.tiff')
print('Wood grain,'+str(np.mean(image)))
image = io.imread('textures/1.1.10.tiff')
print('Raffia,'+str(np.mean(image)))
image = io.imread('textures/1.1.11.tiff')
print('Pigskin,'+str(np.mean(image)))
image = io.imread('textures/1.1.12.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.1.13.tiff')
print('Plastic bubbles,'+str(np.mean(image)))

image = io.imread('textures/1.2.01.tiff')
print('Grass,'+str(np.mean(image)))
image = io.imread('textures/1.2.02.tiff')
print('Bark,'+str(np.mean(image)))
image = io.imread('textures/1.2.03.tiff')
print('Straw,'+str(np.mean(image)))
image = io.imread('textures/1.2.04.tiff')
print('Herringbone weave,'+str(np.mean(image)))
image = io.imread('textures/1.2.05.tiff')
print('Woolen cloth,'+str(np.mean(image)))
image = io.imread('textures/1.2.06.tiff')
print('Pressed calf,'+str(np.mean(image)))
image = io.imread('textures/1.2.07.tiff')
print('Beach sand,'+str(np.mean(image)))
image = io.imread('textures/1.2.08.tiff')
print('Water,'+str(np.mean(image)))
image = io.imread('textures/1.2.09.tiff')
print('Wood grain,'+str(np.mean(image)))
image = io.imread('textures/1.2.10.tiff')
print('Raffia,'+str(np.mean(image)))
image = io.imread('textures/1.2.11.tiff')
print('Pigskin,'+str(np.mean(image)))
image = io.imread('textures/1.2.12.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.2.13.tiff')
print('Plastic bubbles,'+str(np.mean(image)))

image = io.imread('textures/1.3.01.tiff')
print('Grass,'+str(np.mean(image)))
image = io.imread('textures/1.3.02.tiff')
print('Bark,'+str(np.mean(image)))
image = io.imread('textures/1.3.03.tiff')
print('Straw,'+str(np.mean(image)))
image = io.imread('textures/1.3.04.tiff')
print('Woolen cloth,'+str(np.mean(image)))
image = io.imread('textures/1.3.05.tiff')
print('Herringbone weave,'+str(np.mean(image)))
image = io.imread('textures/1.3.06.tiff')
print('Pressed calf leather,'+str(np.mean(image)))
image = io.imread('textures/1.3.07.tiff')
print('Beach sand,'+str(np.mean(image)))
image = io.imread('textures/1.3.08.tiff')
print('Water,'+str(np.mean(image)))
image = io.imread('textures/1.3.09.tiff')
print('Wood grain,'+str(np.mean(image)))
image = io.imread('textures/1.3.10.tiff')
print('Raffia,'+str(np.mean(image)))
image = io.imread('textures/1.3.11.tiff')
print('Pigskin,'+str(np.mean(image)))
image = io.imread('textures/1.3.12.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.3.13.tiff')
print('Plastic bubbles,'+str(np.mean(image)))

image = io.imread('textures/1.4.01.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.4.02.tiff')
print('Wood shingle roof,'+str(np.mean(image)))
image = io.imread('textures/1.4.03.tiff')
print('Wood shingle roof,'+str(np.mean(image)))
image = io.imread('textures/1.4.04.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.4.05.tiff')
print('Tile roof,'+str(np.mean(image)))
image = io.imread('textures/1.4.06.tiff')
print('Wood fence,'+str(np.mean(image)))
image = io.imread('textures/1.4.07.tiff')
print('Metal grates,'+str(np.mean(image)))
image = io.imread('textures/1.4.08.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.4.09.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.4.10.tiff')
print('Grass,'+str(np.mean(image)))
image = io.imread('textures/1.4.11.tiff')
print('Sand,'+str(np.mean(image)))
image = io.imread('textures/1.4.12.tiff')
print('Sand,'+str(np.mean(image)))

image = io.imread('textures/1.5.01.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.5.02.tiff')
print('Hexagonal hole array,'+str(np.mean(image)))
image = io.imread('textures/1.5.03.tiff')
print('Rough wall,'+str(np.mean(image)))
image = io.imread('textures/1.5.04.tiff')
print('Sand,'+str(np.mean(image)))
image = io.imread('textures/1.5.05.tiff')
print('Gravel,'+str(np.mean(image)))
image = io.imread('textures/1.5.06.tiff')
print('Brick wall,'+str(np.mean(image)))
image = io.imread('textures/1.5.07.tiff')
print('Grass,'+str(np.mean(image)))
image = io.imread('textures/texmos1.p512.tiff')
print('USC texture mosaic #1,'+str(np.mean(image)))
image = io.imread('textures/texmos2.p512.tiff')
print('USC texture mosaic #2,'+str(np.mean(image)))
image = io.imread('textures/texmos2.s512.tiff')
print('USC texture mosaic #2 (info),'+str(np.mean(image)))
image = io.imread('textures/texmos3.p512.tiff')
print('USC texture mosaic #3,'+str(np.mean(image)))
image = io.imread('textures/texmos3.s512.tiff')
print('USC texture mosaic #3b,'+str(np.mean(image)))
image = io.imread('textures/texmos3b.p512.tiff')
print('USC texture mosaic #3 (info),'+str(np.mean(image)))



